package roomescape.domain;

public enum DomainErrorCode {
    RESOURCE_NOT_FOUND,
    ALREADY_EXISTS,
    INVALID_INPUT,
    PAST_DATE,
    FORBIDDEN,
    RESOURCE_IN_USE,
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_ALREADY_PROCESSED,
    PAYMENT_INVALID_REQUEST,
    PAYMENT_REJECTED,
    PAYMENT_NOT_FOUND,
    PAYMENT_CONFIGURATION_ERROR,
    PAYMENT_RETRYABLE,
    PAYMENT_FAILED
}
